name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: run test
        run: make test
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: make artifacts
      - uses: actions/upload-artifact@v2
        with:
          name: Generated Artifacts
          path: artifacts.tar.bz2